language: python

env:
  - TOX_ENV=py33
  - TOX_ENV=py34

before_install:
  - sudo add-apt-repository ppa:gns3/ppa -y
  - sudo apt-get update -q

install:
  - pip install tox
  - sudo apt-get install vpcs dynamips

script:
  - tox -e $TOX_ENV

#branches:
#  only:
#    - master

notifications:
  email: false
#  irc:
#    channels:
#      - "chat.freenode.net#gns3"
#    on_success: change
#    on_failure: always

