language: python
python:
  - "3.3"
  - "3.4"

install:
  - python setup.py install
  - pip install -rdev-requirements.txt

script:
    - py.test -v -s tests

#branches:
#  only:
#    - master

notifications:
  email: false
#  irc:
#    channels:
#      - "chat.freenode.net#gns3"
#    on_success: change
#    on_failure: always

