language: python

before_install:
  - "sudo add-apt-repository ppa:gns3/ppa -y"
  - "sudo apt-get update -q"

install:
  - "pip install tox"
  - "sudo apt-get install vpcs dynamips"

script: "python setup.py test"

branches:
  only:
    - master

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#gns3"
    on_success: change
    on_failure: always

